name: Lint GitHub Actions
on:
  push:
    paths:
      - ".github/workflows/*.yml"
  pull_request:
    paths:
      - ".github/workflows/*.yml"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install actionlint
        run: |
          sudo apt-get update
          sudo apt-get install -y actionlint
      - name: Run actionlint
        run: actionlint